# Abdul Wahid Awan 20i-2367 J Lab#10

# Libraries

In [1]:
import numpy as np

# Create a numpy array of int, characters, float and find their shapes

In [6]:
a = np.random.randint(1,10,size=10)
b = np.array(['a','b','c','d','e','f','g','h'])
c = np.array([1.1,2.3,9.8,3.4,19.9,0.9,8.7])
a.shape,b.shape,c.shape

((10,), (8,), (7,))

# Create a zeros, empty, identity , eye and a full array

In [7]:
d = np.zeros((3,3))
e = np.empty((3,3))
f = np.identity(3)
g = np.eye(3,3)
d,e,f,g

(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
        [0.0000000e+000, 0.0000000e+000, 8.2212523e-321],
        [1.3796137e-306, 0.0000000e+000, 0.0000000e+000]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

# Declare an array having the datatype of object, is it possible?

In [10]:
h = np.array([1,2,3,4,5,6,7,8,9,10],dtype=object)
print(h,'Possible')

[1 2 3 4 5 6 7 8 9 10] Possible


# Create an array having 5 equally spaced numbers ranging from 5 to 15

In [11]:
arr = np.linspace(5,15,5)
arr

array([ 5. ,  7.5, 10. , 12.5, 15. ])

# Create a numpy array ranging from 1 to 100

In [12]:
arr = np.arange(1,101)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

# Reshape the above array into (100,15). Is it possible?

In [16]:
try:
    k = np.reshape(arr,(100,15))
except:
    print("Not possible")

Not possible


# Reshape the array into (100,10).


In [17]:
try:
    k = np.reshape(arr,(100,10))
except:
    print("Not possible")

Not possible


# Flatten and ravel the reshaped array. What is the difference?

In [20]:
k = np.reshape(arr,(10,10))
k.flatten(),k.ravel()

(array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
         92,  93,  94,  95,  96,  97,  98,  99, 100]),
 array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  

# Take an array [[1 2 3] [4 5 6] [ 7 8 9]]. Sum it along 0 and 1 axis

In [22]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
zero_sum=arr.sum(axis=0)
one_sum=arr.sum(axis=1)
print(zero_sum)
print(one_sum)

[12 15 18]
[ 6 15 24]


# Find the number of bytes used by your array

In [24]:
arr.nbytes

36

# Find the maximum and minimum values in a 1D array.

In [26]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print('Max: ',arr.max())
print('Min: ',arr.min())

Max:  10
Min:  1


# Find the maximum and minimum values in 2D array

In [28]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Max",arr.max(axis=1),arr.max())
print("Min",arr.min(axis=1),arr.min())

Max [3 6 9] 9
Min [1 4 7] 1


# Sort an array

In [29]:
arr= np.random.randint(1,10,10)
print('Before Sort',arr)
print('After Sort',np.sort(arr))

Before Sort [3 4 1 1 8 7 4 3 3 5]
After Sort [1 1 3 3 3 4 4 5 7 8]


# Is * and mul the same as dot product for numpy arrays and matrices? Check.

In [31]:
p = np.array([1,2,3])
q = np.array([4,5,6])
print('P*Q',p*q)
print('Np.Multiply',np.multiply(p,q))
print('Np.Dot',np.dot(p,q))


P*Q [ 4 10 18]
Np.Multiply [ 4 10 18]
Np.Dot 32


# Take the square root and norm of an array.

In [33]:
arr = np.random.randint(1,10,10)
print('Square Root',np.sqrt(arr))
print('Norm',np.linalg.norm(arr))

Square Root [1.41421356 1.73205081 2.44948974 2.64575131 1.41421356 1.73205081
 1.         2.23606798 2.23606798 2.82842712]
Norm 15.033296378372908


# Find the std, non-zero, zero values and mean of an array.

In [35]:
print("Array: ",r)
print("Std Dev: ",r.std())
print("Non-Zero: ",np.count_nonzero(r))
print("Zero: ",np.count_nonzero(arr==0))
print("Mean: ",arr.mean())

Array:  [2 3 6 7 2 3 1 5 5 8]
Std Dev:  2.227105745132009
Non-Zero:  10
Zero:  0
Mean:  3.9


# Convert some angles to radians and vice versa.

In [38]:
arr = np.array([0,30,45,60,90])
radian = np.radians(arr)
degree = np.degrees(arr)
print("Radians: ",radian)
print("Degrees: ",degree)

Radians:  [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Degrees:  [   0.         1718.87338539 2578.31007809 3437.74677078 5156.62015618]


# Save and load some of your arrays

In [39]:
np.save("array.npy",arr)
np.load("array.npy")

array([ 0, 30, 45, 60, 90])

# Calculate the mean, std, var, max, min, of an array with shape (3,3,12,3) containing floats drawn from a normal distribution with mean 21 and sigma 4.5. see the np.random.normal.

In [41]:
arr = np.random.normal(21,4.5,(3,3,12,3))
print("Mean: ",arr.mean())
print("Std Dev: ",arr.std())
print("Variance: ",arr.var())
print("Max: ",arr.max())
print("Min: ",arr.min())


Mean:  20.311715707206734
Std Dev:  4.5874569648358205
Variance:  21.044761404220676
Max:  34.771833652525146
Min:  3.2751816511883156
